/* Turns the three.js ES module build into a plain <script> global.
 *
 * The shell is offline (CONTRACT 1.2: zero network calls at runtime), and the
 * r160 build ships no UMD bundle any more, so the module build is wrapped by
 * hand: its trailing `export{a as Scene,b as Color,...}` becomes a returned
 * object literal, and the whole thing is wrapped in an IIFE assigned to
 * window.THREE. The game then reads the same THREE.* names it always did.
 *
 *   node Tools/_shell/_three_global.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const src = fs.readFileSync(path.join(HERE, '..', '..', 'sources', 'lib', 'three.module.min.js'), 'utf8');
const m = /export\{([^}]*)\};?\s*$/.exec(src);
if (!m) throw new Error('no export statement found - wrong build?');
const pairs = m[1].split(',').map(function (p) {
  const bits = p.split(/\s+as\s+/);
  const local = bits[0].trim();
  const name = (bits[1] || bits[0]).trim();
  return JSON.stringify(name) + ':' + local;
});
const body = src.slice(0, m.index) + '\nreturn {' + pairs.join(',') + '};\n';
const out = [
  '/* three.js r160 (MIT) - inlined as a global so Midnight Overdrive runs with',
  '   no network at all. Generated by Tools/_shell/_three_global.js from',
  '   sources/lib/three.module.min.js; do not hand-edit. */',
  'window.THREE=(function(){',
  body,
  '})();',
  ''
].join('\n');
fs.writeFileSync(path.join(HERE, 'three.global.js'), out, 'utf8');
console.log('three.global.js: ' + (out.length / 1024).toFixed(0) + ' KB, ' + pairs.length + ' exports');
