'use strict';
/* Downloads the webfonts the six new games reference.
 *
 * WHY: the integrator strips the Google Fonts <link> (the shell is offline and
 * a webfont request could never succeed on a device with no network), but
 * nothing replaced it, so every title fell back to a system font and "lost" its
 * typography.
 *
 * The files are written into app/src/main/assets/fonts/web/ and referenced from
 * the games with a RELATIVE url, so they load straight off the APK with no
 * network call. They are deliberately NOT inlined as base64: that is ~3.3 MB
 * per font, which would multiply by every game that shipped it.
 *
 * Run once (it needs the network); the output is committed, so neither the
 * build nor the device ever does.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT = path.join(__dirname, '..');
const FONT_DIR = path.join(ROOT, 'app', 'src', 'main', 'assets', 'fonts', 'web');
const OUT = path.join(__dirname, '_shell', 'fonts.css');

/* Only the weights the six games actually ask for. */
const FAMILIES = [
  { css: 'Baloo+2:wght@700;800', name: 'Baloo 2' },
  { css: 'Titan+One', name: 'Titan One' },
  { css: 'Cormorant+Garamond:wght@400;700', name: 'Cormorant Garamond' }
];

function get(url, binary) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return get(res.headers.location, binary).then(resolve, reject);
      }
      if (res.statusCode !== 200) { res.resume(); return reject(new Error(url + ' -> ' + res.statusCode)); }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

(async () => {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  let out = ['/* ============================================================',
    '   Embedded webfonts. Generated by Tools/_fetch_fonts.js - do not edit.',
    '',
    '   The shell is offline, so the Google Fonts <link> is stripped from every',
    '   game. These rules point at the real font files shipped in',
    '   app/src/main/assets/fonts/web/, addressed RELATIVE to the game page, so',
    '   the typography is restored without a single network call.',
    '   ============================================================ */',
    ''
  ].join('\n');

  let total = 0;
  for (const f of FAMILIES) {
    const css = await get('https://fonts.googleapis.com/css2?family=' + f.css + '&display=swap', false);
    const blocks = css.split('@font-face').slice(1);
    for (const b of blocks) {
      const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1];
      const style = (b.match(/font-style:\s*(\w+)/) || [])[1] || 'normal';
      const weight = (b.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
      const url = (b.match(/url\((https:[^)]+)\)/) || [])[1];
      if (!fam || !url) continue;
      const bin = await get(url, true);
      const file = fam.replace(/\s+/g, '') + '-' + weight + (style === 'italic' ? 'i' : '') + '.ttf';
      fs.writeFileSync(path.join(FONT_DIR, file), bin);
      total += bin.length;
      /* games live at assets/games/<id>/index.html, fonts at assets/fonts/web/ */
      out += '@font-face{font-family:\'' + fam + '\';font-style:' + style +
        ';font-weight:' + weight + ';font-display:swap;' +
        'src:url(../../fonts/web/' + file + ') format(\'truetype\')}\n';
      console.log('  ' + file.padEnd(28) + (bin.length / 1024).toFixed(0) + ' KB');
    }
  }
  fs.writeFileSync(OUT, out, 'utf8');
  console.log('\nfonts: ' + (total / 1024 / 1024).toFixed(1) + ' MB in ' + FONT_DIR);
  console.log('wrote ' + OUT);
})().catch((e) => { console.error('FAILED: ' + e.message); process.exit(1); });
