"""Embed the display font into Egg Rush as a base64 woff2 data URI.

WHY A SUBSET: CONTRACT 1.2 allows a system font stack or a base64-embedded woff2
(<40KB total) and bans font CDNs. `Tools/_embed_font.py` embedded the FULL
LuckiestGuy TTF into Chicken Chaos, which costs ~97KB of base64 because the file
carries 367 glyphs (Latin Extended-A, currency, math ...) that a game HUD never
renders. Egg Rush only ever draws A-Z, a-z, 0-9, a little punctuation and a few
typographic marks, so this script subsets to exactly those codepoints and packs
the result as woff2 - which lands the whole face far inside the 40KB budget.

WHY base64 AND NOT url('../../fonts/...'): GameActivity sets
allowFileAccessFromFileURLs=false / allowUniversalAccessFromFileURLs=false, so a
file:// page cannot pull a subresource out of a parent asset folder. Chicken
Chaos shipped that relative url first and had to be migrated to base64 (see the
`old`/`new` pair in _embed_font.py) - a data URI bypasses the origin check
entirely, which is why it is the pattern used by every game in this repo.

Re-runnable: the face is rewritten between the two marker comments in the page,
so running this twice is a no-op instead of stacking the base64 up.

Usage:  python Tools/_gen_egg_font.py
"""
import base64
import io

from fontTools import subset
from fontTools.ttLib import TTFont

SRC = "app/src/main/assets/fonts/LuckiestGuy-Regular.ttf"
PAGE = "app/src/main/assets/games/egg-rush/index.html"
START = "/* @font-face:egg-rush:start */"
END = "/* @font-face:egg-rush:end */"

# Everything the HUD, the start page and the canvas text can ever draw.
#   A-Z a-z 0-9          labels, WINNER names, PLAYER n, scores, countdown
#   ASCII punctuation    "P1 0/4", "+2", "GO!", hint sentences, "REDUNDANT STUDIOS"
#   U+2022 bullet        the COLLECT . ROB . RAID tagline
#   U+2014 / U+2013 dash the objective banner
#   U+00D7 multiply      "2x" style copy
#   U+2192 arrow         menu hints
CHARS = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
    " !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
    "\u2022\u2014\u2013\u00d7\u2192\u2018\u2019\u201c\u201d\u2026"
)


def build_woff2():
    """Subset the TTF to CHARS and return the woff2 bytes."""
    font = TTFont(SRC)
    opts = subset.Options()
    opts.layout_features = []        # no GSUB/GPOS needed for a display face
    opts.hinting = False
    opts.desubroutinize = True
    opts.notdef_outline = True
    opts.drop_tables += ["kern"]
    sub = subset.Subsetter(options=opts)
    sub.populate(text=CHARS)
    sub.subset(font)
    font.flavor = "woff2"            # needs the `brotli` module
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def main():
    raw = build_woff2()
    b64 = base64.b64encode(raw).decode()

    face = (
        "/* Display face: LuckiestGuy, subset to the glyphs this game draws and\n"
        "   packed as woff2 so the whole face costs this much base64 (CONTRACT 1.2\n"
        "   allows a system stack or a base64 woff2 under 40KB - no font CDNs).\n"
        "   Generated by Tools/_gen_egg_font.py; re-run that instead of editing. */\n"
        # Declared as a 100-900 range, not 400: the real face is already a fat
        # display cut, but every rule here asks for font-weight:900. Pinning 400
        # would make the browser synthesise a smeared faux-bold on top of it.
        "@font-face{font-family:'Luckiest Guy';font-style:normal;font-weight:100 900;"
        "font-display:block;"
        "src:url(data:font/woff2;base64," + b64 + ") format('woff2')}"
    )

    s = io.open(PAGE, encoding="utf-8").read()
    i, j = s.find(START), s.find(END)
    assert i >= 0 and j > i, "font markers missing from %s" % PAGE
    s = s[:i] + START + "\n" + face + "\n" + END + s[j + len(END):]
    io.open(PAGE, "w", encoding="utf-8", newline="\n").write(s)

    print("subset glyphs : %d -> woff2 %d bytes" % (len(CHARS), len(raw)))
    print("base64        : %d chars (%.1f KB)" % (len(b64), len(b64) / 1024.0))
    print("page          : %d bytes" % len(s))
    assert len(b64) < 40960, "base64 face exceeds the 40KB contract budget"


if __name__ == "__main__":
    main()
