# -*- coding: utf-8 -*-
"""Generates `prompts/<game-id> prompt.md` - one ready-to-hand prompt per game.

Run:  python Tools/_gen_game_prompts.py

WHY A GENERATOR: FuturePlans/GAME_IDEAS.md is the single source of truth for status, players and
proposed manifest values (sections 1, 6 and 12). This script reads that knowledge once,
here, and writes one prompt file per game so a session can be started by pasting a single
file. Edit the DATA below (or FuturePlans/GAME_IDEAS.md first, then here) and re-run - never hand-edit
the generated files, they are overwritten.

The prompt body follows FuturePlans/GAME_IDEAS.md section 12.1 (the game-work request prompt): state
the idea, pin every shell constraint, and say nothing about implementation.
"""
import io
import os

OUT_DIR = 'prompts'

HEADER = u"""# {name} - build prompt

<!-- GENERATED by _gen_game_prompts.py from FuturePlans/GAME_IDEAS.md. Do not hand-edit; edit the data
     in that script and re-run it. The living status of this game lives in FuturePlans/GAME_IDEAS.md. -->

| | |
|---|---|
| RS id | `{rs}` |
| Manifest id | `{id}` |
| Status | {status} |
| Type | {type} |
| Players | {players} |
| Tier | {tier} |
| Orientation | {orientation} |
| Target file | `{target}` |
| Manifest values | `{manifest}` |

## THE IDEA (one paragraph, no more)

{idea}

## THIS GAME'S SPECIFICS

{specifics}

## HARD REQUIREMENTS (our shell stack - all mandatory)

1. ONE self-contained `.html`. All CSS, JS and art inline.
2. ZERO network calls at runtime: no CDNs, no external fonts, no analytics, no remote images.
   It must run perfectly from `file://` with the device offline.
3. Size budget: {tier} - see `CONTRACT.md` §2 (T1 <= 300 KB, T2 <= 450 KB, T3 <= 1 MB).
4. `STUDIO_GAME_MANIFEST` comment block with exactly these keys -
   `id / title / orientation / minPlayers / maxPlayers / aiSupport / online / tileColor / version`
   - values: `{manifest}`.
5. `window.Game` lifecycle with a simulation clock: `pause()`, `resume()`, `destroy()`.
   Pausing must freeze all timers, animation and audio; nothing may keep simulating in the
   background.
6. Studio SDK block, wrapped so the game runs fully when the native bridge is absent
   (browser test).
7. Ads ONLY through the shell bridge (banner + rewarded); a rewarded callback that arrives
   with no argument means GRANTED. If the device is offline, show a plain "check your
   internet connection" message - NEVER a simulated or fake ad.
8. Audio and vibration obey the shell settings (master sound, volume, vibration, haptic
   profile): no game sound may play when master sound is off. `Game.setSettings` receives
   `sound` / `haptics` / `volume` from the shell.
9. User-facing copy: plain text, no em dashes and no "--" anywhere in the UI.
10. Orientation {orientation}, with safe-area insets handled (notches, rounded corners).
11. Every inline `<script>` block must parse - verified with the syntax gate below.

## DO NOT

- Change the shell, add a second file, add a dependency, phone home, or invent gameplay
  beyond the idea above.
- Touch any file other than the target file (and, when the entry says so, the manifest
  block inside it).
- Launch the app or the game yourself. Build and install only; the director tests on device.

## DONE MEANS

- `node Tools/_check_js_syntax.js {target}` -> `ALL SCRIPTS PARSE OK`.
- `BUILD.bat` -> `BUILD OK - shell-debug.apk`, and only then `adb install -r shell-debug.apk`.
- {done}
- `FuturePlans/GAME_IDEAS.md` status updated (and `PROGRESS.md` current state if the game shipped).

## OPEN QUESTIONS FOR THE DIRECTOR

{open}
"""

README = u"""# Game prompts

One file per game: `prompts/<manifest-id> prompt.md`. Each is a **ready-to-hand build
prompt** - paste the whole file into a session to start work on that game. They are
generated by `Tools/_gen_game_prompts.py` from the knowledge in `FuturePlans/GAME_IDEAS.md` (§1 status
board, §6 entries, §12 prompt contract); regenerate with:

    python Tools/_gen_game_prompts.py

`FuturePlans/GAME_IDEAS.md` remains the single source of truth for status, players and decisions.
These files only restate it as a request, so a session never has to guess the constraints.
They are overwritten on every run - edit the script, never the generated files.

| File | RS id | Status |
|---|---|---|
{table}
"""


GAMES = [
    dict(rs='RS-001', id='ludo', name='Ludo', status='SHIPPED (v14) - frozen', type='Board',
         players='2-4 + bots', tier='Tier 1', orientation='portrait',
         target='app/src/main/assets/games/ludo/index.html',
         manifest='id ludo / portrait / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor #D94B4B / version 14',
         idea='Four seats race one track, a capture sends a pawn home, and all the tension lives in the last '
              'few squares. Two to four players on one phone, bots filling empty seats. This is the shipped '
              'reference for what a finished board game looks like in this shell.',
         specifics=[
             'Shipped and stable: use this prompt as the SHAPE reference for a finished game, not as work.',
             'Change it only for a director-reported issue - the manifest block, lifecycle and settings sync '
             'are already correct here.',
             'Keep the ranking and the 10x bot test in dev mode working after any change; that is this game\'s '
             'regression net.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6 (shipped reference entries).',
         ],
         done='No change beyond the reported issue, and the 10x bot test still completes in dev mode.',
         open=['Report the exact behaviour to change; the game is otherwise frozen.']),
    dict(rs='RS-002', id='planetmerge', name='Planet Merge', status='SHIPPED (parked with a director issue list)',
         type='Puzzle', players='1', tier='Tier 1', orientation='portrait',
         target='app/src/main/assets/games/planetmerge/index.html',
         manifest='id planetmerge / portrait / minPlayers 1 / maxPlayers 1 / aiSupport none / online false / tileColor #E8912F / version 1',
         idea='Drop and merge celestial bodies, chase a longer chain, never top out. A calm single-player '
              'puzzle-toy that has to feel tactile on a phone. It ships today, but the director parked a list '
              'of issues on it, so this is a FIX session and not a rewrite.',
         specifics=[
             'Use the fix-session shape from FuturePlans/GAME_IDEAS.md section 12.3: scope is ONLY the issues listed in '
             'the session.',
             'The rollback copies that used to sit in the repo root (backup/previous known-good files) are '
             'gone: the shipped file plus version control is the only history now, so read the whole file '
             'before you change a line.',
             'Keep the manifest block, the `window.Game` lifecycle and the strip/physics behaviour intact '
             'unless an issue says otherwise.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6 (Planet Merge, phase 1).',
         ],
         done='Only the listed issues changed, and everything that worked before still works.',
         open=['Give the issue list at the start of the session - it defines the entire scope.']),
    dict(rs='RS-003', id='chess', name='Chess', status='SHIPPED (v0.7.1) - puzzle work continues',
         type='Classic', players='1-2 (+bot)', tier='Tier 1', orientation='portrait',
         target='app/src/main/assets/games/chess/index.html',
         manifest='id chess / portrait / minPlayers 1 / maxPlayers 2 / aiSupport full / online false / tileColor #8A5A44 / version 0.7.1',
         idea='Real chess against a bot that actually searches, with a puzzle as the reason to come back '
              'tomorrow. One player, portrait, pass-and-play for two. The engine is done; what is left is the '
              'puzzle pack and its onboarding.',
         specifics=[
             'Do NOT rewrite the engine: move generation (castling, en passant), FEN load/save, negamax + '
             'alpha-beta + quiescence, undo and per-move juice all work.',
             'PUZZLE DATA: `sources/LockedGames/chess_puzzles.txt` (Lichess, 10 500 entries, buckets '
             'easy/normal/hard, shape '
             '`[puzzleId, FEN, solutionMoves, rating, themes]`) is 2.6 MB and must NOT ship as-is. Ship a '
             'packed subset that fits the budget and report the count. Runtime asset: `games/chess/puzzles.js` '
             '- regenerate with `python Tools/_gen_puzzles.py`.',
             'Puzzle rules: the player must play the stored solution move(s); a wrong move gets a gentle shake '
             'and a retry, no timer.',
             'Rewarded ads (shell bridge only, never simulated) may gate a larger puzzle pack.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.1.',
         ],
         done='Puzzle subset size reported, wrong-move retry verified on device, rewarded gate works through '
              'the shell bridge, both themes checked.',
         open=['How many puzzles ship (it drives the file budget)?', 'Top bot strength vs file size?']),
    dict(rs='RS-004', id='checkers', name="Checkers - Gould's Problems", status='DATA ONLY - no game built around it',
         type='Puzzle', players='1', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/checkers/index.html',
         manifest='proposed: id checkers / portrait / minPlayers 1 / maxPlayers 1 / aiSupport none / online false / tileColor ink-charcoal / version 1',
         idea='Six hundred and seventy-eight real historical checkers problems solved one at a time - a pure '
              '"next puzzle" loop with no timer and no luck. The player reads the board, finds the win, moves '
              'on.',
         specifics=[
             'DATA TRUTH: `sources/Playable Games/CHeckers_puzzels_goulds_problems_all.json` (260 KB) holds '
             '678 puzzles after '
             'de-duplication by FEN+result, 487 with kings. Difficulty is a piece-count heuristic (easy <= 6, '
             'normal 7-10, hard >= 11), NOT a source label. Entry shape: `{id, fen, side, white[], black[], '
             'kingsW[], kingsB[], result, difficulty}`.',
             'Nothing exists around the data: no board renderer, no solution checker, no manifest. Next to '
             'the JSON sit `checkers.html` and a pending-fixes brief (`chekcers_pending fixes.txt`), all in '
             '`sources/Playable Games/`.',
             'DECIDE FIRST: stored solutions per problem (verifiable) or "player reports a win, next problem".',
             'It is a puzzle, not an opponent: `aiSupport none`. Full entry: FuturePlans/GAME_IDEAS.md section 6.2.',
         ],
         done='A readable board renderer, a completion rule matching the decision above, the manifest block, and '
              'the puzzle set inside the single file within budget.',
         open=['Stored solutions, or player-reported wins?', 'How many of the 678 ship first?']),
    dict(rs='RS-005', id='bomb-relay', name='Bomb Relay', status='PLAYABLE - needs shell',
         type='Party', players='1-4 + bots', tier='Tier 1', orientation='portrait',
         target='port source: sources/Playable Games/BombRelay.html -> app/src/main/assets/games/bomb-relay/index.html',
         manifest='proposed: id bomb-relay / portrait / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor fuse-red / version 1',
         idea='Pass the phone, the bomb is ticking, and the holder must complete the mini-challenge to '
              'survive. Whoever holds it when the fuse hits 0:00 loses. One to four players share one device, '
              'and the phone flips between turns so people sitting opposite can play.',
         specifics=[
             'Already built: pass-n-play 1-4 with per-player colours, bot seats, mini-games with hints, the '
             'pass animation, the flip for the next human, fuse countdown with escalating warnings, free '
             'hint/skip, round-based solo with a local best, portrait lock.',
             'MISSING: the `STUDIO_GAME_MANIFEST` block (the shell cannot see the game) and a real '
             '`window.Game` lifecycle that freezes the sim clock.',
             'Ads: replace the in-file stub with real calls through the shell bridge (rewarded for hint/skip). '
             'Offline shows the plain message, never a fake ad.',
             'Verify the pass-and-flip UX on a real phone in hand - it was built in a browser.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.3.',
         ],
         done='Manifest + lifecycle added, ads routed through the bridge, and a full pass-and-flip round played '
              'on device without a hitch.',
         open=['Which mini-games are launch content?', 'Hint/skip free in solo and rewarded in party?']),
    dict(rs='RS-006', id='last-balloon', name='Last Balloon', status='PLAYABLE - needs shell',
         type='Party', players='1-4 + bots', tier='Tier 1', orientation='portrait',
         target='port source: sources/Playable Games/LastBaloon.html -> app/src/main/assets/games/last-balloon/index.html',
         manifest='proposed: id last-balloon / portrait / minPlayers 1 / maxPlayers 4 / aiSupport true / online false / tileColor sky-blue / version 1',
         idea='Hold the pump, inflate the balloon, hand it on before it pops. Greed is funny right up until '
              'it is not. One to four players, one phone, turns that last five seconds.',
         specifics=[
             'Already built: hold-to-pump with release to end the turn, a meter that exaggerates while the real '
             'limit stays secret and shifts every game, creak/sweat/panic tells near that limit, bot personas, '
             'optional rotation between turns (1&3 vs 2&4), rematch + home, backyard ambience, local best.',
             'MISSING: the manifest block and the `window.Game` lifecycle.',
             'Audio: the tells must go silent when shell master sound is off and must obey shell volume.',
             'Check the balloon art at the smallest supported screen size.',
             'Ads: banner only - rewarded would break the tension curve. Full entry: FuturePlans/GAME_IDEAS.md section 6.4.',
         ],
         done='Manifest + lifecycle added, tells obey master sound and volume, art checked small, one full '
              'four-player round played on device.',
         open=['Is the "creak" cue alone enough, or does it need a second tell? (playtest, not code)']),
    dict(rs='RS-007', id='monopoly-ish', name='Monopoly-style property board game',
         status='IDEA (researched, not started) - the director\'s favourite',
         type='Board', players='2-6 (bots are phase 2)', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/monopoly-ish/index.html',
         manifest='proposed: id monopoly-ish / portrait / minPlayers 2 / maxPlayers 6 / aiSupport none at launch / online false / tileColor #2E9E5B / version 1',
         idea='Family game night on one phone: roll, buy, collect, ruin your friendships - on our own board, '
              'with our own cards, our own currency and our own name. Two to six players pass one device and a '
              'whole game fits inside one sitting.',
         specifics=[
             'IP WARNING, the biggest risk here: *Monopoly* is a Hasbro trademark and its board art, logo, '
             'card text and piece names are protected. The mechanics of property-trading games belong to nobody '
             '(they go back to *The Landlord\'s Game*, 1903). Ship NO Hasbro trade dress and never the name in '
             'the app, the store listing or the keywords.',
             'BOARD: a shorter track - 7x7 perimeter = 24 spaces instead of 40 - fewer property groups, one '
             'price tier per group, no mortgages at launch. India board first (our city list, our railway '
             'junctions, our own utility pair). Boards are data, so a second board is a list, not a game.',
             'Session: a fixed 45-minute ceiling plus a quick-rules mode of about 20 minutes.',
             'Trading is the soul: offer -> counter -> accept must complete in three taps.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.5.',
         ],
         done='A complete 2-4 player pass-n-play game ending by bankruptcy or the timer, on our India board, '
              'with our card deck and no protected trade dress anywhere in the file.',
         open=['Confirm the game\'s own name (nothing with "Monopoly" in it).',
               'Confirm the 24-space track and the 45-minute ceiling.',
               'Bots at launch, or phase 2 as proposed?']),
    dict(rs='RS-008', id='party-pack', name='Party Pack (shell section + the small party games)', status='IDEA',
         type='Party', players='group on one phone', tier='Tier 1', orientation='portrait',
         target='pilot: new file app/src/main/assets/games/party-clue-and-guess/index.html (+ a PARTY entry point in the shell)',
         manifest='proposed pilot: id party-clue-and-guess / portrait / minPlayers 3 / maxPlayers 8 / aiSupport none / online false / tileColor party-pink / version 1',
         idea='A pack of shout-out-loud party games for one phone passed around a room: clue-and-guess, dumb '
              'charades and truth-or-dare, each turn short and loud enough to be funny from across a table.',
         specifics=[
             'Three launch modules: 1) CLUE & GUESS - one player sees a word and gives clues while the group '
             'guesses against a timer (the pilot). 2) DUMB CHARADES - the phone shows a word to the actor only, '
             'with categories and difficulty tiers. 3) TRUTH OR DARE - a local deck, clean/classic by default, '
             'with an explicit age toggle.',
             'SHELL WORK THIS IMPLIES (not built yet): a manifest `category` field '
             '(`board|classic|party|arena|puzzle`) parsed next to the others, plus a PARTY entry point on Home '
             '(the way ALL GAMES works) or a filter on the Mode screen. Reuse the existing pass-and-flip '
             'mechanics instead of inventing them.',
             'Policy: local-only (no network, so no online-interaction declaration). Ads: banner on results '
             'only. Truth-or-dare content must be tame by default; age rating and content review are real '
             'tasks, not line items.',
             'Group-sized type: one small screen read at arm\'s length. Full entry: FuturePlans/GAME_IDEAS.md section 6.6.',
         ],
         done='The pilot module (Clue & Guess) playable end-to-end on device, the `category` field parsed by the '
              'shell, and a PARTY entry point visible on Home.',
         open=['Agree the three launch modules.', 'Who writes the content deck?',
               'A PARTY band on Home, or a filter on the Mode screen?']),
    dict(rs='RS-009', id='snakes-ladders', name='Snakes & Ladders', status='IDEA',
         type='Classic / family', players='2-4 + bots', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/snakes-ladders/index.html',
         manifest='proposed: id snakes-ladders / portrait / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor warm sand / version 1',
         idea='Nobody\'s favourite game, everybody\'s ten minutes: the fastest session in the pack (two to '
              'three minutes) and the one a parent plays with a kid. Roll, hop, climb a ladder, get bitten, '
              'race to the end.',
         specifics=[
             'The honest read: the game has zero decisions, so all the design work is FEEL AND SPEED. Its job '
             'in the pack is to be the shortest, juiciest, most colourful tile - not the deepest.',
             'Build: a 10x10 board as pure data (snakes/ladders tables per board, so a new board is a list), '
             'animated pawn hops, bump-off when landing on an occupied square (the only real interaction the '
             'game can have), roll-again on a 6 so a turn never stalls, and a full-screen bitten/climbed moment '
             'with shake, floating text and sfx.',
             'Twist candidates - pick ONE for launch and keep a pure mode: bribe the snake (spend a token to '
             'climb instead), pick your ladder (one reroll per player per game), or the Indian board identity '
             '(temple steps, mango-tree ladders, kites and monsoon clouds - vaikuntapali flavour). The third '
             'costs nothing extra and is the most "us".',
             'The bot is trivial (it just rolls), so `aiSupport true` from day one.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.7.',
         ],
         done='One full 2-4 player game in under three minutes with no dead turns, the chosen twist working, and '
              'the board readable by a child.',
         open=['Choose the single twist and the board theme before building.']),
    dict(rs='RS-010', id='daadi', name='Daadi / Dhadi (the chalk-and-stones game)', status='IDEA (rules researched and verified)',
         type='Classic / heritage', players='2 + bots', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/daadi/index.html',
         manifest='proposed: id daadi / portrait / minPlayers 2 / maxPlayers 2 / aiSupport true / online false / tileColor chalk-white on slate grey / version 1',
         idea='The game the Andhra fisherfolk were said to be impossible to beat: drawn on the ground with '
              'chalk, played with stones. Zero luck, pure thinking, and it is ours.',
         specifics=[
             'It is the NINE MEN\'S MORRIS family (Telugu Daadi / Dhadi, from దాడి "attack"; also Navakankari, '
             'Saalu Mane Ata, Jodpi Ata, Muhle). Board: three concentric squares joined by mid-lines = 24 '
             'points, 9 pieces each. Phases: placing (a mill of three removes an enemy piece), then moving along '
             'the lines (another mill, another capture). Flying when down to 3 pieces. Win by reducing the '
             'opponent to 2 pieces or blocking every legal move.',
             'OPEN QUESTION: the director remembered "two squares" (a beginner variant). Decide whether to ship '
             'the 24-point board only, or both as beginner + full.',
             'Build: the board is a GRAPH - 24 nodes, 32 edges, plus the line sets that form mills. State = node '
             'occupancy; win check = fewer than 3 pieces or zero legal moves. Bot: negamax with material + mills '
             '+ mobility + blocked-enemy evaluation.',
             'Art direction (the reason this idea is strong): chalk lines on sand or rock, two kinds of stone as '
             'pieces, a shoreline background, gulls and surf as ambience.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.8.',
         ],
         done='Board renderer + mill/win logic correct, a full game to a win on device, and the heritage art in '
              'place without hurting readability.',
         open=['Which variant: 24-point only, or two-square beginner + 24-point full?']),
    dict(rs='RS-011', id='tic-tac-toe', name='Tic Tac Toe (juice + a twist)', status='IDEA',
         type='Classic', players='1-2 + bots', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/tic-tac-toe/index.html',
         manifest='proposed: id tic-tac-toe / portrait / minPlayers 1 / maxPlayers 2 / aiSupport true / online false / tileColor chalk cyan / version 1',
         idea='The world\'s smallest game. The only reason to ship it is to ship the best-feeling version of it, '
              'plus one twist nobody expects.',
         specifics=[
             'Honest read: classic 3x3 with perfect play is a forced draw, so plain it is a wasted tile. Ship it '
             'as a THREE-MODE package in one file.',
             'Modes: 1) CLASSIC (juiced) - dust on placement, winning-line glow, screen shake, a perfect hard bot '
             'that taunts a little. 2) MISERE - three in a row LOSES (a tiny rule change, a real brain teaser, no '
             'extra code). 3) ULTIMATE - nine small boards in a 3x3 meta-grid; the square you play sends your '
             'opponent to the matching board. This is the selling point.',
             'Bots: perfect play via negamax for Classic and Misere (tiny state space); depth-limited search for '
             'Ultimate - strong but fallible.',
             'Public-domain folk game: no IP concerns at all.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.9.',
         ],
         done='All three modes playable on device, Ultimate rules correct (including the won-board redirect), and '
              'the juice present in Classic.',
         open=['Does Ultimate ship at launch? (recommended: yes - it is the selling point)']),
    dict(rs='RS-012', id='pen-fight', name='Pen Fight', status='PLAYABLE - has director-reported issues',
         type='Arena', players='2-5 + AI', tier='Tier 2 (physics)', orientation='landscape',
         target='port source: sources/Playable Games/PenFight.html -> app/src/main/assets/games/pen-fight/index.html',
         manifest='proposed: id pen-fight / landscape / minPlayers 2 / maxPlayers 5 / aiSupport true / online false / tileColor ink blue / version 1',
         idea='Desk-warfare nostalgia: pull back, release, flick your rival\'s pen off the bench. Real-time '
              'physics, up to five players sharing one screen.',
         specifics=[
             'CONTRACT VIOLATION TO FIX FIRST: the file loads Matter.js from a CDN, so the game fails offline '
             '("Couldn\'t load the physics engine"). Inline matter.js (minified ~150 KB, total ~230 KB, inside '
             'the Tier-2 budget) or replace it with our own tiny circle-vs-circle collision code.',
             'MISSING: the manifest block, and a real lifecycle - `pause` / `destroy` and sim-clock freezing are '
             'not implemented, so a backgrounded game keeps simulating.',
             'AI quality is the weakest area: heuristic aim at the nearest enemy plus a power search over a small '
             'candidate set, then tune.',
             'Physics must feel repeatable and stay time-based, never frame-based (frame rate changes flick '
             'distance). The layout must let five players each reach a control on one screen.',
             'ASK THE DIRECTOR which "serious issues" were meant. Provable from the code: the CDN dependency, the '
             'missing manifest/lifecycle, AI difficulty. Full entry: FuturePlans/GAME_IDEAS.md section 6.10.',
         ],
         done='Runs fully offline from file://, manifest + lifecycle in place, a full 2-5 player round played on '
              'device with the AI feeling fair.',
         open=['Which issues did you mean by "serious issues"? They go to the top of this prompt.',
               'Inline matter.js, or write our own tiny collision code?']),
    dict(rs='RS-013', id='connect-four', name='Connect Four', status='IDEA',
         type='Classic', players='1-2 + bots', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/connect-four/index.html',
         manifest='proposed: id connect-four / portrait / minPlayers 1 / maxPlayers 2 / aiSupport true / online false / tileColor cobalt blue / version 1',
         idea='Drop, clack, connect: the classic with real gravity and a satisfying thunk, plus one variant that '
              'makes the board live again.',
         specifics=[
             'Build: a 7x6 grid, drop animation with a bounce, falling-dust particles, a winning-line glow with '
             'shake, and a bot. Highlight the column while aiming so it feels physical.',
             'THE DESIGN CATCH: Connect Four is a SOLVED game - with perfect play the first player always wins. '
             'So cap the hard bot at a depth where it is strong but FALLIBLE (a depth-7 search with a scoring '
             'tweak), or the player is guaranteed to lose when going second.',
             'Ship at least ONE variant mode as the differentiator. Candidates: POP (a player may remove one of '
             'their own bottom pieces, which re-opens the board), POWER COLUMNS (one column drops a bomb that '
             'clears the square below), BLITZ (10-second turns, so the clock becomes the game).',
             'The game tree is tiny: minimax + alpha-beta with a small transposition table is enough.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.11.',
         ],
         done='Drop feel + win detection verified on device, the chosen variant working, and the hard bot losing '
              'to good play sometimes.',
         open=['Which variant ships? (recommended: Pop - it is a real rule and it fixes the solved-game boredom)']),
    dict(rs='RS-014', id='dots-and-boxes', name='Dots & Boxes', status='IDEA',
         type='Classic', players='1-4 + bots', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/dots-and-boxes/index.html',
         manifest='proposed: id dots-and-boxes / portrait / minPlayers 1 / maxPlayers 4 / aiSupport true / online false / tileColor graphite/violet / version 1',
         idea='The notebook game everyone played in school, but with a combo counter and a bot that punishes a '
              'careless chain.',
         specifics=[
             'Why it deserves a tile: it has a real strategic layer - the DOUBLE-CROSS sacrifice (give your '
             'opponent a short chain so they must open a long one for you). Depth with zero luck.',
             'Build: grid sizes as data (4x4 beginner, 6x6 standard, 8x8 expert), tap a gap to draw a line, a box '
             'completion animation with a colour wash in the owner\'s colour, a CHAIN-COMBO counter that '
             'escalates sound and pitch per box in a run, and a "one more box!" pulse. In 2-4 player mode every '
             'line keeps its owner\'s colour so the board stays readable.',
             'Bots: greedy first (always take a free box), then chain-aware - count chains, avoid opening a long '
             'chain, use the double-cross when behind on parity. That progression gives three difficulty tiers '
             'for free.',
             'Optional twists (pick at most one): a bonus box worth 3, a rare bomb line that clears adjacent '
             'claimed boxes, or a timed Blitz mode.',
             'Banner ads only. Full entry: FuturePlans/GAME_IDEAS.md section 6.12.',
         ],
         done='Grid + line/box model correct at all three sizes, the greedy and chain-aware bots both feel right '
              'on device, and the combo escalation is audible.',
         open=['Do any twists ship at launch, or is the chain-aware bot the whole pitch?']),
    dict(rs='RS-015', id='chicken-chaos', name='Chicken Chaos', status='SHIPPED (v4) and LOCKED',
         type='Arena', players='2-4 + bots', tier='Tier 1', orientation='landscape',
         target='app/src/main/assets/games/chicken-chaos/index.html',
         manifest='id chicken-chaos / landscape / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor #6BCB4A / version 4',
         idea='Grab the chicken, dash away, do not get tackled: a same-screen scramble where everyone fights over '
              'one bird. The game ships today, is locked, and needs nothing - this prompt exists as the reference '
              'for what a finished landscape arena game looks like in this shell.',
         specifics=[
             'LOCKED: do not start work on this game unless the director explicitly reopens it. Its contract is '
             'complete: manifest v4 with a changelog block, the Studio SDK, the full `window.Game` lifecycle, '
             'settings sync (sound / haptics / volume via `Game.setSettings`), gesture-gated audio unlock, and '
             'the landscape turn owned by the shell (no WebView fullscreen call).',
             'Shipped rules: SCORE = chickens caught. No target score and no early win path; a match always runs '
             'the full 60 s and the player with the most catches wins (ties are called as ties).',
             'Shipped presentation, so it is not accidentally undone: in-game texts are viewport-scaled captions, '
             'back/gear use the game\'s own unselected-toggle face, the in-game pause keeps its original dark '
             'translucent disc, catch boxes stay smaller than the pause button, and the result card is a cream '
             'board with a grass paddock + the start-page chicken on the left and the win/tie headline (TIME UP! '
             'styling) plus the catch table on the right.',
             'Ads: the interstitial runs when the player taps PLAY AGAIN or MENU on the result card - never over '
             'the result itself.',
             'Full history: FuturePlans/GAME_IDEAS.md section 6.13 and the manifest changelog inside the file.',
         ],
         done='Nothing to do. If reopened: the syntax gate passes, the build installs, and only the director\'s '
              'named items change.',
         open=['Only reopen this game with a specific director-requested change.']),
    dict(rs='RS-016', id='egg-rush', name='Egg Rush', status='PLAYABLE - the manifest is the blocker',
         type='Arena', players='2-4 + bots', tier='Tier 1', orientation='landscape',
         target='port source: sources/Playable Games/EggRush.html -> app/src/main/assets/games/egg-rush/index.html',
         manifest='proposed: id egg-rush / landscape / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor warm egg-yellow / version 1',
         idea='Collect, rob, raid: hoard eggs, steal them off rivals and get them home. A same-screen landscape '
              'arena where a big lead is also a target on your back.',
         specifics=[
             'Already built: a landscape arena, hens as players (red/yellow/blue/purple = P1-P4), egg states '
             '(loose / carried / delivered), golden eggs with a multiplier counter, a race mode with a target '
             'score, bot count and "eggs to win" settings, a RACE ONLY option, steal/rob between players, dash + '
             'magnet + shield power-ups, particles, a win panel with winner identity, and PLAY AGAIN.',
             'Already present: the Studio SDK block and a lifecycle (`pause` / `resume` / `destroy`). MISSING: '
             'the `STUDIO_GAME_MANIFEST` block - that is the main blocker - plus the syntax gate and a landscape '
             'device test.',
             'DESIGN NOTE: rob/steal means a leader can be punished constantly. Tune the "carrying makes you '
             'slower" mechanic so a big lead is risky but not impossible; that tension is the whole joke.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.14.',
         ],
         done='Manifest added, syntax gate green, and a full landscape race played on device (including one '
              'rob-a-leader moment that felt fair).',
         open=['Confirm the tile colour.', 'Does race mode ship enabled by default?']),
    dict(rs='RS-017', id='memory-grab', name='Memory Grab', status='PLAYABLE - needs shell (and a file rename)',
         type='Party', players='2+ / vs AI', tier='Tier 1', orientation='portrait',
         target='port source: sources/Playable Games/MemeoryGrab.html -> app/src/main/assets/games/memory-grab/index.html',
         manifest='proposed: id memory-grab / portrait / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor #8E6FD8 / version 1',
         idea='Remember, match, score: memory pairs passed around the room with no timer pressure. Turn-based '
              'party play on one phone, and a board that stays facing you in BOTS mode.',
         specifics=[
             'Already built: cards start face-down, tap one to reveal and a second to match (match = +1 and you '
             'keep your turn; no match = they hide and play passes on), the SCREEN TURNS AROUND on turn change '
             '("pass the phone!"), no timer at all, and it ends when every pair is found with the highest score '
             'winning. Menus: PLAY TOGETHER / PLAY VS AI / SELECT PLAYERS / GAME PAUSED / MAIN MENU / MEMORY '
             'COMPLETE / FINAL SCORE, plus a short-viewport guard.',
             'Already present: the Studio SDK block and the lifecycle. MISSING: the manifest block.',
             'RENAME: the source file is `sources/Playable Games/MemeoryGrab.html` (typo). The shipped folder '
             'must be `memory-grab`, so '
             'the typo never becomes the manifest id.',
             'Future content: card sets are just data (animals, food, flags, our own art).',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.15.',
         ],
         done='Manifest added, file renamed to `memory-grab`, and a full 4-player pass-and-flip game plus one '
              'BOTS game played on device.',
         open=['How many card sets at launch?']),
    dict(rs='RS-018', id='balloon-battle', name='Balloon Battle', status='PLAYABLE - needs shell',
         type='Arena', players='2-4', tier='Tier 1', orientation='landscape',
         target='port source: sources/Playable Games/balloonFight.html -> app/src/main/assets/games/balloon-battle/index.html',
         manifest='proposed: id balloon-battle / landscape / minPlayers 2 / maxPlayers 4 / aiSupport true / online false / tileColor #F2724B / version 1',
         idea='Grab the pin, pop their balloons: a sky-island scramble where the pin is the only weapon and '
              'everybody wants it.',
         specifics=[
             'Already built: a sky-island arena, a pin that spawns on a timer with a GOT THE PIN / PIN EXPIRED '
             'cycle, power-ups (shield, dash, speed) dropping out of bubbles, obstacles with proper collision '
             'push-out, elimination with draw and winner detection, floating text and particles, a per-player '
             'nameplate HUD, a seat-mapped layout (P1/P2 bottom, locked seats) for 2-4 on one screen, and a '
             'landscape guard.',
             'MISSING: the `STUDIO_GAME_MANIFEST` block and the Studio SDK block.',
             'NAMING COLLISION to resolve with Last Balloon (RS-006): two balloon games must not read the same in '
             'the grid. Fix the titles and tile art so they are obviously different games.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.16.',
         ],
         done='Manifest + SDK in place, a full 2-4 player round played on device in landscape, and the pin cycle '
              'readable the first time.',
         open=['Confirm the tile colour and the new title against Last Balloon.']),
    dict(rs='RS-019', id='letter-press', name='Letter Press (the typing game)', status='IDEA',
         type='Party', players='1-2', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/letter-press/index.html',
         manifest='proposed: id letter-press / portrait / minPlayers 1 / maxPlayers 2 / aiSupport none / online false / tileColor print-ink / version 1',
         idea='A print-shop typing game: letters come down the page and you stamp them with the pads you have, '
              'under a press that keeps speeding up.',
         specifics=[
             'Theme: a print shop. The pads (keys) CHANGE and GROW per wave, so the player is always learning a '
             'new layout instead of drilling one muscle memory.',
             'Typing games live or die on latency and legibility: input must be judged on the same frame it '
             'arrives, and the falling text must be CRISP.',
             'PERFORMANCE LESSON FROM CHICKEN CHAOS (already paid for): never write `ctx.letterSpacing` inside a '
             'per-frame text helper - it forces a re-shape every frame. Cache the shaped text instead.',
             'Players: 1-2 (two pads, or a hot-seat race).',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.17.',
         ],
         done='A full run at the target wave count on device with no dropped input, and the text stable in '
              'frame time (no per-frame re-shaping).',
         open=['How many waves is a session?', 'Does it need a per-word bonus layer, or is speed the only score?']),
    dict(rs='RS-020', id='cliff-rise', name='Cliff Rise (the floating-tiles crossing)', status='IDEA',
         type='Party (party + solo in ONE file)', players='1-6', tier='Tier 1', orientation='portrait',
         target='new file: app/src/main/assets/games/cliff-rise/index.html',
         manifest='proposed: id cliff-rise / portrait / minPlayers 1 / maxPlayers 6 / aiSupport none / online false / tileColor #78909C / version 1',
         idea='The bridge is a lie. Every row of floating tiles has one safe landing: pick it, or fall into the '
              'sky. Knowledge is shared, so the room gets louder with every row.',
         specifics=[
             'IS IT A PARTY GAME? Yes, but only in this form: a group sharing one device, short loud turns, and '
             'reactions worth watching. A bridge where every column is a blind coin flip is a lottery, not a '
             'game - what makes it a party game is that the bridge STAYS REVEALED for the whole round, so each '
             'player learns from the ones who fell.',
             'Core loop: the group stands on the near cliff. The field is N columns wide (2-5, scaling with the '
             'round) and one row taller each time. On your turn you pick a column and hop: a solid tile thuds '
             'and you advance, a fake tile shatters, the screen shakes and you lose a life. That row\'s safe '
             'column is now known to everyone.',
             'TWO MODES IN ONE FILE (do not ship a second file): PARTY (2-6 players, 3 lives each, last one '
             'standing wins, rounds add columns and hazards - a tile that cracks on the SECOND landing is a '
             'great late-round twist) and SOLO (endless climb for the best row count). Solo has nobody to learn '
             'from, so its fake tiles carry a TELL that gets subtler as you climb: a faint seam, a missing '
             'rivet, a one-frame shimmer - solo is a perception game, party is memory and nerve. Same bridge '
             'generator, two skills.',
             'A mode toggle on the start screen costs one variable; a second file would duplicate about 70% of '
             'the code and the two copies would drift. This is recorded so it is not re-litigated.',
             'Juice: tile crack and shatter, a real fall (scale down + spin + the tile shrinking in '
             'perspective), wind streaks on a near-miss hop, screen shake on impact, a swelling heartbeat as the '
             'row count rises. Party mode gets one extra: whoever falls leaves a GHOST PLATE on that column, so '
             'the board visibly records the dead.',
             'Risks: the whole game is one decision repeated, so the tell system and the per-round twists must '
             'carry it, and a 6-player round must take about 90 seconds, not five.',
             'Full entry: FuturePlans/GAME_IDEAS.md section 6.18.',
         ],
         done='Both modes playable on device: a 6-player party round inside 90 seconds with the ghost plates '
              'reading clearly, and a solo run where the tell is fair but not obvious.',
         open=['Confirm both modes ship in one file (recommended).', 'How many rows is a good solo ceiling?']),
]


def bullet_block(items):
    return u'\n'.join(u'- ' + i for i in items)


def main():
    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)
    rows = []
    for g in GAMES:
        body = HEADER.format(
            name=g['name'], rs=g['rs'], id=g['id'], status=g['status'], type=g['type'],
            players=g['players'], tier=g['tier'], orientation=g['orientation'],
            target=g['target'], manifest=g['manifest'], idea=g['idea'],
            specifics=bullet_block(g['specifics']),
            done=g['done'], open=bullet_block(g['open']))
        path = os.path.join(OUT_DIR, g['id'] + ' prompt.md')
        io.open(path, 'w', encoding='utf-8', newline='\n').write(body)
        rows.append('| `' + g['id'] + ' prompt.md` | ' + g['rs'] + ' | ' + g['status'] + ' |')
        print('  ' + path)
    io.open(os.path.join(OUT_DIR, 'README.md'), 'w', encoding='utf-8', newline='\n').write(
        README.replace('{table}', '\n'.join(rows)).replace('{count}', str(len(GAMES))))
    print('wrote ' + str(len(GAMES)) + ' game prompts + README.md into ' + OUT_DIR + '/')


if __name__ == '__main__':
    main()
